version: '3'
services:
  restapp:
    build: .
    volumes:
      - ./server:/server
    networks:  # <-- here
      - svgapi_network
  nginx: 
    image: nginx:alpine
    ports:
      - 80:80
    container_name: svgapi_nginx
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:  # <-- wait for webapp to be "ready" before starting this service
      - restapp
    networks:  
      - svgapi_network
  redis:
    image: redislabs/rejson:latest 
    networks:  
      - svgapi_network
    ports:
      - 6379:6379
    volumes:     
      - redis_data:/data        
volumes:  
  redis_data:
networks:  
  svgapi_network:
    driver: bridge              
    
